### ISSUE TITLE
Hide dock then show dock only when MouseOver

### ISSUE THREAD

**Issue by TauLieR64** [nitesh-prasad/Quantum-Dock#2]
Hi,
Good job for your dock, this is awesome and really easy to adapt.

**But i'm stuck at 1 thing :**

I wonder if there's a way to hide dock all the time then show dock only when mouseOver ?
I tried but i'm beginner with LUA and rainmeter.

Thanks for your answer.

**Comment by Psycpus** [comment]
Hello,
In case you still need help;

First of all, open Rainmeter, then click on Quantum Dock's "Taskbar.ini" file, from the right side panel open "Transparency" dropdown menu and choose 0%, lastly open "On hover" dropdown menu and choose "Fade in".

Hope this helps!

**Comment by TauLieR64** [comment]
> Hello, In case you still need help;
> 
> First of all, open Rainmeter, then click on Quantum Dock's "Taskbar.ini" file, from the right side panel open "Transparency" dropdown menu and choose 0%, lastly open "On hover" dropdown menu and choose "Fade in".
> 
> Hope this helps!

Thank you for your answer, I'm gonna give it a try ASAP.

Edit : that works perfectly. Thank you again.
